import { FoodItem, Category, Reward } from './types';

export const CATEGORIES: Category[] = [
  'Burgers',
  'Meal Deals',
  "Sandwich's",
  'All Day Breakfast',
  'HotDogs',
  'Kebabs',
  'Crispy Chicken',
  'Drinks',
  'Trays'
];

export const MENU_ITEMS: FoodItem[] = [
  {
    id: 'c1',
    name: 'Warden’s Crunch',
    category: 'Crispy Chicken',
    price: 12000,
    shortDescription: 'Locked in with our Jailbirds secret recipe. Full-size wings seasoned deep to the bone, lightly coated for a thin golden crunch — tender, juicy, and seriously addictive.',
    fullDescription:
      'Locked in with our special Jailbirds secret recipe, these full-size chicken wings are seasoned deep to the bone and sealed with our signature blend of premium herbs and spices. Each wing is lightly coated for that perfect golden crisp — thin, crunchy, and irresistibly mouth-watering — while the inside stays tender, juicy, and cooked to perfection.\n\nOur unique Jailbirds-style cooking method keeps all the flavour sealed in, delivering a bold taste that will leave you coming back for more… and more.\n\nAvailable as a single order or as part of a full meal set — because once you\'ve had a taste, one is never enough.',
    deliveryCharge: 0,
    deliveryTime: '25-35 min',
    freeGift: 'Prison Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/chicken%20crispy.png',
  },
  {
    id: 'c2',
    name: 'Warden’s Crunch + Rice',
    category: 'Crispy Chicken',
    price: 36000,
    shortDescription: 'Crispy Jailbirds wings, marinated deep and sealed with our premium herb blend. Thin golden crunch outside, juicy inside — served with a fluffy portion of white boiled rice.',
    fullDescription:
      'Locked down with our exclusive Jailbirds secret blend, these full-size chicken wings are marinated deep to the bone and infused with a bold mix of premium herbs and spices. Every wing is lightly coated to achieve that perfect golden crunch — thin, crispy, and seriously satisfying — while the inside remains tender, juicy, and cooked just right.\n\nPrepared using our signature Jailbirds-style method, the flavour is sealed in tight, delivering a rich, punchy taste that keeps you coming back for another bite… and then another.\n\nServed with 1 portion of fluffy white boiled rice, making it a complete and satisfying meal. Available as a single order or as part of a full meal set — because once you\'ve tried it, one serving is never enough.',
    deliveryCharge: 0,
    deliveryTime: '25-35 min',
    freeGift: 'Prison Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/chicken%20crispy%20with%20rice.png',
  },
  {
    id: 'c3',
    name: 'Warden’s Crunch Special',
    category: 'Crispy Chicken',
    price: 39000,
    shortDescription: 'Crispy wings sealed with our Jailbirds secret blend. Served with fluffy boiled rice and set sauces — curry, extra hot lava, and creamy cheese — for the ultimate combo.',
    fullDescription:
      'Sealed tight with our exclusive Jailbirds secret blend, these full-size chicken wings are marinated right down to the bone and packed with a bold fusion of premium herbs and spices. Each wing is lightly coated to create that perfect golden crunch — thin, crispy, and seriously addictive — while the inside stays tender, juicy, and cooked to perfection.\n\nPrepared the signature Jailbirds way, every bite locks in that rich, punchy flavour that keeps you reaching for more… and then more again.\n\nAnd because we all love that famous Jailbirds sauce, you can now order your chicken wings and rice with our set sauces included — curry sauce, extra hot lava sauce, and creamy cheese sauce — giving you the ultimate flavour combo in every meal.\n\nServed with one portion of fluffy white boiled rice, this dish makes a complete and satisfying feast. Available as a single order or as part of a full meal deal — because once you\'ve tasted it, one serving is never enough.',
    deliveryCharge: 0,
    deliveryTime: '25-35 min',
    freeGift: 'Prison Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/chicken%20crispy%20with%20sauce.png',
  },
  {
    id: 'c4',
    name: 'Cell Block Fire Bites',
    category: 'Crispy Chicken',
    price: 23000,
    shortDescription: 'Locked and loaded with serious heat. Tender chicken bites in a crispy golden coating, seasoned with our bold spicy blend — served with blazing Lava Hot Sauce.',
    fullDescription:
      'Locked and loaded with serious heat, our Cell Block Fire Bites are made from tender, juicy chicken wrapped in a crispy, golden coating that delivers the perfect crunch in every bite. Seasoned with our bold spicy blend, these nuggets bring the fire from the first bite to the last.\n\nServed with our blazing Lava Hot Sauce, made to ignite any true spice lover\'s taste buds — this is not for the faint-hearted. Crispy on the outside, tender on the inside, and packed with full-on flavour.\n\n⚠️ Warning: Maximum heat. No early release. 🔥',
    deliveryCharge: 0,
    deliveryTime: '25-35 min',
    freeGift: 'Prison Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/chicken%20nuggets%20mealsssss.png',
  },
  {
    id: 'b1',
    name: 'The Solitary Burger',
    category: 'Burgers',
    price: 45000,
    shortDescription: 'Double beef patty with secret "shack" sauce.',
    fullDescription: 'Our signature double beef patty burger, seasoned with prison-grade spices, topped with melted cheddar, caramelized onions, and our top-secret solitary sauce. Served on a toasted brioche bun.',
    deliveryCharge: 5000,
    spicyLevel: 1,
    deliveryTime: '25-35 min',
    freeGift: 'Prison Sticker',
    image: 'https://picsum.photos/seed/burger1/600/600'
  },
  {
    id: 'b2',
    name: 'Maximum Security Stack',
    category: 'Burgers',
    price: 65000,
    shortDescription: 'Triple patty, triple cheese, triple trouble.',
    fullDescription: 'For the hungriest inmates. Three premium beef patties, triple layers of American cheese, crispy bacon, jalapenos, and spicy mayo. Not for the faint of heart.',
    deliveryCharge: 5000,
    spicyLevel: 2,
    deliveryTime: '30-40 min',
    freeGift: 'Extra Napkins',
    image: 'https://picsum.photos/seed/burger2/600/600'
  },
  {
    id: 'm2',
    name: 'JailYard Tower Meal',
    category: 'Meal Deals',
    price: 45000,
    shortDescription: 'A crispy, golden chicken fillet topped with melted cheese, fresh sliced tomatoes, crunchy iceberg lettuce, and sliced onions, all packed inside a soft, freshly baked bun.',
    fullDescription: 'Includes:\n- Medium: Tower Burger + 250ml Drink + Medium Fries\n- Large: Tower Burger + 390ml Drink + Large Fries\n\nStep into the yard with the Jail Yard Tower – a stacked-up chicken burger built for serious hunger.\n\nA crispy, golden chicken fillet topped with melted cheese, fresh sliced tomatoes, crunchy iceberg lettuce, and sliced onions, all packed inside a soft, freshly baked bun. Every ingredient is freshly prepared and cooked to order for maximum flavor in every bite.\n\nServed with a hot portion of crispy fries and your choice of refreshing soft drink to complete the combo.\n\n🔥 Bonus: This meal deal also includes a FREE ATM Leather Jailbirds Wallet – tough, stylish, and built to last.\n\nFresh buns. Fresh ingredients. Freshly cooked.\nThe Jail Yard Tower isn’t just a meal… it’s a full yard experience.',
    deliveryCharge: 0,
    deliveryTime: '35-45 min',
    freeGift: 'FREE ATM Leather Jailbirds Wallet',
    image: 'https://ik.imagekit.io/7grri5v7d/chicken%20burger%20mean%20wallets.png'
  },
  {
    id: 'm3',
    name: 'Warden’s Parole Meal',
    category: 'Meal Deals',
    price: 48000,
    shortDescription: 'The Warden’s Parole Meal is built to keep your energy levels on high alert, packed with protein and stacked for serious satisfaction.',
    fullDescription: 'Includes:\n- Medium: Warden’s Parole Burger + 250ml Drink + Medium Fries\n- Large: Warden’s Parole Burger + 390ml Drink + Large Fries\n\nThe Warden’s Parole Meal is built to keep your energy levels on high alert, packed with protein and stacked for serious satisfaction. This burger starts with a freshly pan-fried bun, layered with Jailbirds special sauce, then loaded with golden fries, rich sauced beans, a juicy sausage, and topped with a perfectly fried egg and fried onion. Served with crispy fries, a cold drink of your choice, and a free ATM leather wallet.',
    deliveryCharge: 0,
    deliveryTime: '35-45 min',
    freeGift: 'FREE ATM Leather Jailbirds Wallet',
    image: 'https://ik.imagekit.io/7grri5v7d/wardens%20meal%20dealss.png'
  },
  {
    id: 'm4',
    name: 'Day Break Meal',
    category: 'Meal Deals',
    price: 44000,
    shortDescription: 'The Warden’s Day Break is a powerful meal designed to keep your energy high and your hunger locked down, packed with mouth watering flavours in every bite.',
    fullDescription: 'Includes:\n- Medium: Warden’s Day Break Burger + 250ml Drink + Medium Fries\n- Large: Warden’s Day Break Burger + 390ml Drink + Large Fries\n\nThe Warden’s Day Break is a powerful meal designed to keep your energy high and your hunger locked down, packed with mouth watering flavours in every bite. Built inside a freshly pan-fried bun, it’s layered with Jailbirds special sauce, stacked with golden fries, then creamy coleslaw with rich mayo sauce, followed by a juicy sausage and finished with a perfectly fried egg and fried onions. Served with a side of hot fries, a cold drink of your choice, and a free ATM leather wallet.',
    deliveryCharge: 0,
    deliveryTime: '35-45 min',
    freeGift: 'FREE ATM Leather Jailbirds Wallet',
    image: 'https://ik.imagekit.io/7grri5v7d/wardens%20meal%20dealssx.png'
  },
  {
    id: 'm5',
    name: 'Tower Max Meal',
    category: 'Meal Deals',
    price: 43000,
    shortDescription: 'Jailbirds’ special sauce, golden fries, creamy coleslaw, a juicy chicken burger, a freshly fried egg, and sliced onions, all sealed inside a fresh soft bun.',
    fullDescription: 'Includes:\n- Medium: Tower Max Burger + 250ml Drink + Medium Fries\n- Large: Tower Max Burger + 390ml Drink + Large Fries\n\nThe Tower Max stacks high for serious flavour and is built to crush any appetite. Layered with Jailbirds’ special sauce, golden fries, creamy coleslaw, a juicy chicken burger, a freshly fried egg, and sliced onions, all sealed inside a fresh soft bun.\n\nThis loaded tower meal is served with crispy fries and a cold drink of your choice — the ultimate feed when hunger hits hard.',
    deliveryCharge: 0,
    deliveryTime: '35-45 min',
    freeGift: 'FREE ATM Leather Jailbirds Wallet',
    image: 'https://ik.imagekit.io/7grri5v7d/ssssssssddd.png'
  },
  {
    id: 'm6',
    name: 'Chicken Max Meal',
    category: 'Meal Deals',
    price: 47000,
    shortDescription: 'Stacked high and built for serious appetite, Chicken Max is loaded with bold Jailbirds flavour from top to bottom — crispy fries, sauced beans, melted cheese, and a cold drink to finish the lockup.',
    fullDescription: 'Includes:\n- Medium: Chicken Max Burger + 250ml Drink + Medium Fries\n- Large: Chicken Max Burger + 390ml Drink + Large Fries\n\nStacked high and built for serious appetite, the Chicken Max is loaded with bold Jailbirds flavour from top to bottom. It starts with a fresh soft bun, layered with Jailbirds special sauce, followed by crispy golden fries and rich sauced beans. On top sits a juicy chicken burger, melted cheese, a perfectly fried egg, and fresh sliced onion, all sealed with a toasted bun.\n\nServed as a full meal with crispy French fries and a cold drink of your choice — this one delivers big taste in every bite.',
    deliveryCharge: 0,
    deliveryTime: '35-45 min',
    freeGift: 'FREE ATM Leather Jailbirds Wallet',
    image: 'https://ik.imagekit.io/7grri5v7d/ssssssssdddxxxx.png'
  },
  {
    id: 'm7',
    name: 'Cell Block Fire Bites Meal',
    category: 'Meal Deals',
    price: 44000,
    shortDescription: 'Crispy fire bites with maximum heat, served with medium golden fries and a cold drink. Fully locked in flavour — for spice lovers only.',
    fullDescription: 'Includes:\n- Medium: Cell Block Fire Bites + 250ml Drink + Medium Fries\n- Large: Cell Block Fire Bites + 390ml Drink + Large Fries\n\nLocked and loaded with serious heat, our Cell Block Fire Bites are made from tender, juicy chicken wrapped in a crispy, golden coating that delivers the perfect crunch in every bite. Seasoned with our bold spicy blend, these nuggets bring the fire from the first bite to the last.\n\nServed with our blazing Lava Hot Sauce to kick every spice lover’s taste buds into overdrive — this one brings maximum heat with no early release.\n\nThis fiery combo comes complete with medium golden French fries and a refreshing cold drink to cool things down… if you can handle the heat.\n\nCrispy. Tender. Spicy. Fully locked in flavour. 🔥',
    deliveryCharge: 0,
    deliveryTime: '35-45 min',
    freeGift: 'FREE ATM Leather Jailbirds Wallet',
    image: 'https://ik.imagekit.io/7grri5v7d/chicken%20nuggets%20meal.png'
  },
  {
    id: 's1',
    name: 'Toasted Chicken',
    category: "Sandwich's",
    price: 28000,
    shortDescription: 'Pressed and toasted to lock in the flavour. This compact, flavour-packed sandwich is loaded with tender seasoned chicken, sweet caramelised onions, fresh tomatoes, and melted cheese.',
    fullDescription: 'Pressed and toasted to lock in the flavour. This compact, flavour-packed sandwich is loaded with tender seasoned chicken, sweet caramelised onions, fresh tomatoes, and melted cheese. Toasted until golden and crispy on the outside, hot, rich, and perfectly melted inside.\n\nWarm, cheesy, and satisfying in every bite.',
    deliveryCharge: 0,
    deliveryTime: '25-35 min',
    freeGift: 'Prison Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/ssssssssdddxxxxnn.png'
  },
  {
    id: 's2',
    name: 'Smoked Beef Toasted',
    category: "Sandwich's",
    price: 29000,
    shortDescription: 'Pressed and toasted to lock in the flavour. This compact, flavour-packed sandwich is loaded with smoky sliced beef, sweet caramelised onions, fresh tomatoes, and melted cheese.',
    fullDescription: 'Pressed and toasted to lock in the flavour. This compact, flavour-packed sandwich is loaded with smoky sliced beef, sweet caramelised onions, fresh tomatoes, and melted cheese. Grilled until golden and crispy on the outside, hot and rich on the inside.\n\nEvery bite is warm, cheesy, smoky perfection.',
    deliveryCharge: 0,
    deliveryTime: '25-35 min',
    freeGift: 'Prison Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/smokey%20toastedd.png'
  },
  {
    id: 's3',
    name: 'Special Chicken + Coleslaw',
    category: "Sandwich's",
    price: 38000,
    shortDescription: 'Pressed and toasted to lock in the flavour. Tender seasoned chicken, sweet caramelised onions, fresh tomatoes, and melted cheese — served with a fresh creamy coleslaw portion.',
    fullDescription: 'Toasted Special Chicken Sandwich with a fresh coleslaw portion, pressed and toasted to lock in the flavour. Filled with tender seasoned chicken, sweet caramelised onions, fresh tomatoes, melted cheese, and creamy coleslaw. Crispy outside, soft and savoury inside, delicious in every bite.',
    deliveryCharge: 0,
    deliveryTime: '25-35 min',
    freeGift: 'Prison Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/smokey%20toasteddss.png?updatedAt=1772631045935'
  },
  {
    id: 's4',
    name: 'Chicken Salad Sandwich',
    category: "Sandwich's",
    price: 38000,
    shortDescription: 'Freshly made with soft white bread layered with creamy mayonnaise, crisp lettuce, and juicy tomatoes.',
    fullDescription: 'Freshly made with soft white bread layered with creamy mayonnaise, crisp lettuce, and juicy tomatoes. Filled with tender grated chicken, sliced cheese, fresh onion, and an extra touch of mayo for rich, smooth flavour, then finished with a top layer of soft bread.\n\nLight, fresh, and satisfying — with the option to enjoy it with a freshly brewed coffee for the perfect combo.',
    deliveryCharge: 0,
    deliveryTime: '25-35 min',
    freeGift: 'Prison Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/chicken%20sandwichss.png'
  },
  {
    id: 's5',
    name: 'Smoked Beef Salad',
    category: "Sandwich's",
    price: 37000,
    shortDescription: 'Made fresh with soft white bread spread with creamy mayonnaise, layered with crisp lettuce and juicy tomatoes.',
    fullDescription: 'Made fresh with soft white bread spread with creamy mayonnaise, layered with crisp lettuce and juicy tomatoes. Filled with tender cooked smoked beef, sliced cheese, fresh onion, and an extra touch of mayo for a rich, smooth flavour, then topped with a soft layer of bread.\n\nFresh, flavourful, and satisfying — with the option to add a freshly brewed coffee to complete your meal.',
    deliveryCharge: 0,
    deliveryTime: '25-35 min',
    freeGift: 'Prison Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/smokey%20%20sandwichss.png'
  },
  {
    id: 'a1',
    name: 'The Salad Sausage Roll',
    category: 'All Day Breakfast',
    price: 48000,
    shortDescription: 'Jumbo fried sausage with fresh salad and creamy mayo coleslaw, topped with golden fried diced onions and tasty fried mushrooms — served with hot black coffee.',
    fullDescription: 'All Day Breakfast is a hearty meal that brings together bold flavours and satisfying textures. A jumbo fried sausage is served with a fresh salad and creamy mayo coleslaw, finished with golden fried diced onions and a line of tasty fried mushrooms. This filling plate is perfect any time of day and comes with a hot black coffee to complete the meal.',
    deliveryCharge: 5000,
    deliveryTime: '20-30 min',
    freeGift: 'Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/all%20day%20breakfast%20s.png'
  },
  {
    id: 'a2',
    name: 'Salad Sausage Roll with Egg',
    category: 'All Day Breakfast',
    price: 36000,
    shortDescription: 'Jumbo fried sausage with a freshly fried egg, golden diced onions, and savoury fried mushrooms — served with a soft buttered roll and hot black coffee.',
    fullDescription: 'All Day Breakfast is a hearty plate made for any time of the day. A jumbo fried sausage is served with a freshly fried egg, golden fried diced onions, and a line of savoury fried mushrooms. This satisfying breakfast is paired with a soft buttered roll and a hot black coffee, delivering a simple yet flavourful meal that keeps you going',
    deliveryCharge: 5000,
    deliveryTime: '20-30 min',
    freeGift: 'Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/all%20day%20breakfast%20sfd.png'
  },
  {
    id: 'a3',
    name: 'Sausage Sandwich',
    category: 'All Day Breakfast',
    price: 43000,
    shortDescription: 'Fresh white bread lightly spread with butter, filled with a juicy jumbo sausage and tomato red sauce — served hot with black coffee.',
    fullDescription: 'The All Day Breakfast Sausage Sandwich is a simple and satisfying classic. Made with fresh white bread lightly spread with butter, it’s filled with a juicy jumbo sausage and finished with a touch of tomato red sauce for extra flavour. Served hot with a cup of black coffee, this hearty sandwich is perfect for breakfast or any time of the day.',
    deliveryCharge: 5000,
    deliveryTime: '20-30 min',
    freeGift: 'Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/sauage%20sanwichs.png'
  },
  {
    id: 'a5',
    name: 'Sausage Sax',
    category: 'All Day Breakfast',
    price: 49000,
    shortDescription: 'Fresh oven bread filled with scrambled eggs, jumbo cut sausages, and melted cheese — served hot with black coffee.',
    fullDescription: 'The Sausage Sax Breakfast – All Day is a hearty sandwich designed to kick-start your morning. Made with fresh bread straight from the oven, it’s filled with fluffy scrambled eggs, layered with juicy jumbo cut sausages, and finished with melted cheese for rich flavour in every bite. Served hot with a cup of black coffee, this satisfying combo is perfect for breakfast any time of the day.',
    deliveryCharge: 5000,
    deliveryTime: '20-30 min',
    freeGift: 'Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/breakfast%20scrambled%20eggs.png'
  },
  {
    id: 'a6',
    name: 'Breco Sandwich',
    category: 'All Day Breakfast',
    price: 54000,
    shortDescription: 'Fresh morning bread with baked beans, jumbo chicken sausage, golden fried onions, and a fried egg — served with black coffee.',
    fullDescription: 'The Breco Sandwich is a warm and satisfying all-day breakfast made with fresh bread baked early in the morning and lightly spread with butter. It’s filled with hearty baked beans, layered with a juicy jumbo chicken sausage, topped with golden fried onions and a freshly fried egg. Served with a hot cup of black coffee, this flavourful sandwich is a perfect way to start the day or enjoy any time.',
    deliveryCharge: 5000,
    deliveryTime: '20-30 min',
    freeGift: 'Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/eggs.png'
  },
  {
    id: 'h1',
    name: 'Chain Gang Dog',
    category: 'HotDogs',
    price: 35000,
    shortDescription: 'Jumbo sausage with mustard and relish.',
    fullDescription: 'A massive 8-inch beef frankfurter topped with classic yellow mustard, sweet pickle relish, and diced onions. Simple, effective, classic.',
    deliveryCharge: 5000,
    deliveryTime: '20-30 min',
    freeGift: 'Sticker',
    image: 'https://picsum.photos/seed/hotdog1/600/600'
  },
  {
    id: 'h3',
    name: 'Sausage Roll Salad',
    category: 'HotDogs',
    price: 33000,
    shortDescription: 'A jumbo fried sausage served with creamy mayo coleslaw, topped with golden fried diced onions and perfectly fried mushrooms.',
    fullDescription: 'The Jailbirds Sausage Roll Salad is packed with bold flavour and satisfying bites. A jumbo fried sausage is served alongside a creamy mayo coleslaw salad, topped with golden fried diced onions and a line of perfectly fried mushrooms. Fresh, hearty, and full of savoury taste, this dish delivers a rich combination of textures and mouth-watering flavour in every bite.',
    deliveryCharge: 5000,
    deliveryTime: '20-30 min',
    freeGift: 'Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/hot%20dog%20coleslawssss.png'
  },
  {
    id: 'k1',
    name: 'The Fugitive Kebab',
    category: 'Kebabs',
    price: 55000,
    shortDescription: 'Succulent lamb with garlic sauce.',
    fullDescription: 'Thinly sliced marinated lamb, wrapped in a warm flatbread with fresh lettuce, tomatoes, onions, and a generous drizzle of our homemade garlic yogurt sauce.',
    deliveryCharge: 5000,
    spicyLevel: 1,
    deliveryTime: '25-35 min',
    freeGift: 'Mini Salad',
    image: 'https://picsum.photos/seed/kebab1/600/600'
  },
  {
    id: 't1',
    name: 'Lockdown Tray',
    category: 'Trays',
    price: 120000,
    shortDescription: 'Feeds 3-4 inmates. Variety of everything.',
    fullDescription: 'A massive sharing tray containing 2 mini burgers, 2 hot dogs, a pile of kebabs, and a mountain of fries. Perfect for a cell block party.',
    deliveryCharge: 10000,
    spicyLevel: 2,
    deliveryTime: '45-60 min',
    freeGift: '4x Stickers',
    image: 'https://picsum.photos/seed/tray1/600/600'
  },
  {
    id: 'b3',
    name: 'The Snitch Burger',
    category: 'Burgers',
    price: 42000,
    shortDescription: 'Chicken breast with spicy slaw.',
    fullDescription: 'Crispy fried chicken breast, spicy cabbage slaw, pickles, and honey mustard sauce. It tells on your hunger.',
    deliveryCharge: 5000,
    spicyLevel: 1,
    deliveryTime: '20-30 min',
    freeGift: 'Sticker',
    image: 'https://picsum.photos/seed/burger3/600/600'
  },
  {
    id: 'b4',
    name: 'Solitary Mushroom',
    category: 'Burgers',
    price: 48000,
    shortDescription: 'Vegetarian patty with portobello.',
    fullDescription: 'A thick grilled portobello mushroom, swiss cheese, arugula, and truffle mayo. Even vegetarians get locked up.',
    deliveryCharge: 5000,
    deliveryTime: '25-35 min',
    freeGift: 'Sticker',
    image: 'https://picsum.photos/seed/burger4/600/600'
  },
  {
    id: 'b5',
    name: 'Day Break Burger',
    category: 'Burgers',
    price: 55000,
    shortDescription: 'Wake up your taste buds with bold, balanced flavour — special sauce, crispy fries, creamy coleslaw, sausage, fried egg, and caramelised onions stacked in one bite.',
    fullDescription: 'Wake up your taste buds with the bold and balanced flavors of the Day Break Burger. Built from the ground up on a soft, freshly toasted bun layered with Jailbirds’ signature special sauce, this powerhouse burger delivers the perfect morning kick.\n\nCrispy golden fries add crunch, followed by fresh, creamy coleslaw for a cool contrast. A juicy, savory sausage takes center stage, topped with a perfectly fried egg and sweet caramelized fried onions. Finished with the top bun, every bite is stacked with texture, flavor, and satisfaction.\n\nThis isn’t just a burger — it’s a full day breakfast packed into one unforgettable bite.',
    deliveryCharge: 5000,
    deliveryTime: '25-35 min',
    freeGift: 'Prison Sticker',
    image: 'https://ik.imagekit.io/7grri5v7d/chicken%20burger%20new.png'
  },
  {
    id: 'h2',
    name: 'The Yard Dog',
    category: 'HotDogs',
    price: 38000,
    shortDescription: 'Chili cheese dog with jalapenos.',
    fullDescription: 'Beef frankfurter topped with spicy beef chili, melted cheddar cheese, and fresh jalapenos. Hotter than the yard in July.',
    deliveryCharge: 5000,
    spicyLevel: 3,
    deliveryTime: '20-30 min',
    freeGift: 'Sticker',
    image: 'https://picsum.photos/seed/hotdog2/600/600'
  },
  {
    id: 'd1',
    name: 'Prison Hooch',
    category: 'Drinks',
    price: 15000,
    shortDescription: 'Homemade fruit punch (Non-alcoholic).',
    fullDescription: 'Our special blend of tropical fruits, served ice cold. Refreshing enough to make you forget you\'re in the mess hall.',
    deliveryCharge: 2000,
    deliveryTime: '10-15 min',
    freeGift: 'Sticker',
    image: 'https://picsum.photos/seed/drink1/600/600'
  },
  {
    id: 'd2',
    name: 'Black Coffee',
    category: 'Drinks',
    price: 12000,
    shortDescription: 'Strong, dark, and bitter.',
    fullDescription: 'Just like the warden\'s heart. Premium local beans, roasted dark and served hot.',
    deliveryCharge: 2000,
    deliveryTime: '10-15 min',
    freeGift: 'Sticker',
    image: 'https://picsum.photos/seed/drink2/600/600'
  }
];

export const REWARDS: Reward[] = [
  {
    id: 'r1',
    name: 'Free Solitary Burger',
    stickersRequired: 10,
    description: 'Redeem 10 stickers for our signature burger.',
    image: 'https://picsum.photos/seed/reward1/400/400'
  },
  {
    id: 'r2',
    name: 'The Jailbird Hoodie',
    stickersRequired: 50,
    description: 'Exclusive orange hoodie with "Inmate" branding.',
    image: 'https://picsum.photos/seed/reward2/400/400'
  },
  {
    id: 'r3',
    name: 'Lifetime 10% Discount',
    stickersRequired: 100,
    description: 'Become a "Trusty" and get 10% off every order forever.',
    image: 'https://picsum.photos/seed/reward3/400/400'
  }
];
